jms_serializer:
  visitors:
    xml:
      format_output: '%kernel.debug%'
  metadata:
    auto_detection: true
    directories:
      app:
        path: "%kernel.root_dir%/../src/Resources/config/serializer"