nelmio_api_doc:
    documentation:
#        schemes: [http, https]
        info:
            title: User Management API
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
        definitions:
            NotFoundError:
                description: "Not found error"
                type: object
                properties:
                    code:
                        type: integer
                        example: 404
                    message:
                        type: string
                        example: "Not found."
            ValidationError:
                descrition: "Validation error"
                type: "object"
                properties:
                    code:
                        type: interger
                        example: 422
                    message:
                        type: string
                        example: "Invalid entity"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc